[build]
  command = "npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev" 
  port = 5000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
